#
# Expect / Tcl wrapper for IPLD REPL
#

#
# Spawn the repl
#

set timeout -1
spawn ipldrepl /tmp/ipld_store
set repl_id $spawn_id

proc add { paths } {
	global repl_id

	set s ""
	foreach p $paths {
		set s "$s \"$p\""
	}

	send -i $repl_id "(add (path $s))\n"

	expect -i $repl_id "\n"
	expect -i $repl_id "\n"
	set cid [lindex [regexp -inline {^z[a-zA-Z0-9]*} $expect_out(buffer)] 0]
	return $cid
}

set cid [add "$argv"]

puts "got a CID '$cid'"
